### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AvangionQ** [pkillthetoy/tenno_mod#2]
05:51:45.763 INFO ThMod.ThMod> ThMod : Card used : DefensiveThrow_TENNO ; cost : 1
Exception: java.lang.NullPointerException
05:51:45.768 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at com.megacrit.cardcrawl.actions.common.DamageAllEnemiesAction.<init>(DamageAllEnemiesAction.java:24) ~[?:?]
	at com.megacrit.cardcrawl.actions.common.DamageAllEnemiesAction.<init>(DamageAllEnemiesAction.java:37) ~[?:?]
	at tenno_mod.cards.common.DefensiveThrow_TENNO.use(DefensiveThrow_TENNO.java:46) ~[tenno_mod.TennoMod.jar:?]
	at com.evacipated.cardcrawl.mod.hubris.patches.ZylophonePatch$MultiUse.use(ZylophonePatch.java:51) ~[Hubris.jar:?]
	at com.megacrit.cardcrawl.characters.AbstractPlayer.useCard(AbstractPlayer.java:1594) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:297) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:159) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:279) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2554) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:878) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
Game closed.

**Comment by AvangionQ** [comment]
Happened again ...

06:50:41.332 INFO ThMod.ThMod> ThMod : Card used : DefensiveThrow_TENNO ; cost : 1
Exception: java.lang.NullPointerException
06:50:41.339 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at com.megacrit.cardcrawl.actions.common.DamageAllEnemiesAction.<init>(DamageAllEnemiesAction.java:24) ~[?:?]
	at com.megacrit.cardcrawl.actions.common.DamageAllEnemiesAction.<init>(DamageAllEnemiesAction.java:37) ~[?:?]
	at tenno_mod.cards.common.DefensiveThrow_TENNO.use(DefensiveThrow_TENNO.java:46) ~[tenno_mod.TennoMod.jar:?]
	at com.evacipated.cardcrawl.mod.hubris.patches.ZylophonePatch$MultiUse.use(ZylophonePatch.java:51) ~[Hubris.jar:?]
	at com.megacrit.cardcrawl.characters.AbstractPlayer.useCard(AbstractPlayer.java:1594) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:297) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:159) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:279) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2554) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:878) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
Game closed.

**Comment by AvangionQ** [comment]
One more time ...

07:19:59.807 INFO basemod.BaseMod> publish on post power apply
07:19:59.808 INFO basemod.BaseMod> powers modified
07:20:00.408 INFO infinitespire.InfiniteSpire> Lucky Rock
07:20:00.408 INFO slimebound.SlimeboundMod> Patch hit.
07:20:00.441 INFO basemod.BaseMod> publish on card use
07:20:00.442 INFO ThMod.ThMod> ThMod : Card used : DefensiveThrow_TENNO ; cost : 1
Exception: java.lang.NullPointerException
07:20:00.448 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at com.megacrit.cardcrawl.actions.common.DamageAllEnemiesAction.<init>(DamageAllEnemiesAction.java:24) ~[?:?]
	at com.megacrit.cardcrawl.actions.common.DamageAllEnemiesAction.<init>(DamageAllEnemiesAction.java:37) ~[?:?]
	at tenno_mod.cards.common.DefensiveThrow_TENNO.use(DefensiveThrow_TENNO.java:46) ~[tenno_mod.TennoMod.jar:?]
	at com.evacipated.cardcrawl.mod.hubris.patches.ZylophonePatch$MultiUse.use(ZylophonePatch.java:51) ~[Hubris.jar:?]
	at com.megacrit.cardcrawl.characters.AbstractPlayer.useCard(AbstractPlayer.java:1594) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:297) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:159) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:279) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2554) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:878) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
Game closed.

**Comment by AvangionQ** [comment]
One last time ...

07:53:42.396 INFO ThMod.ThMod> ThMod : Card used : ReplayTheSpireMod:Book of Names ; cost : 1
07:53:42.406 INFO relics.MummifiedHand> COST IS 0: Void Radiance
07:53:42.407 INFO relics.MummifiedHand> COST IS 0: Lethal Torrent
07:53:42.408 INFO relics.MummifiedHand> COST IS 0: I.O.U.
07:53:42.408 INFO relics.MummifiedHand> COST IS 0: Banana+
07:53:42.409 INFO relics.MummifiedHand> COST IS 0: Concealed Weapons
07:53:42.409 INFO relics.MummifiedHand> INVALID: Book of Names+
07:53:42.413 INFO relics.MummifiedHand> INVALID: Defensive Throw
07:53:42.414 INFO relics.MummifiedHand> VALID CARDS: 
07:53:42.414 INFO relics.MummifiedHand> Rolling Guard+
07:53:42.414 INFO relics.MummifiedHand> Void Dash+
07:53:42.414 INFO relics.MummifiedHand> Defensive Throw+
07:53:42.414 INFO relics.MummifiedHand> Void Strike+
07:53:42.414 INFO relics.MummifiedHand> Umbral Howl
07:53:42.414 INFO relics.MummifiedHand> Umbral Intensify+
07:53:42.414 INFO relics.MummifiedHand> Void Dash
07:53:42.417 INFO relics.MummifiedHand> Mummified hand: Umbral Intensify+
07:53:43.130 INFO basemod.BaseMod> publish on post power apply
07:53:43.131 INFO basemod.BaseMod> powers modified
07:53:43.230 INFO basemod.BaseMod> publish on post power apply
07:53:43.231 INFO basemod.BaseMod> powers modified
07:53:43.330 INFO basemod.BaseMod> publish on post power apply
07:53:43.331 INFO basemod.BaseMod> powers modified
07:53:43.680 INFO basemod.BaseMod> publish on card use
07:53:43.681 INFO ThMod.ThMod> ThMod : Card used : DefensiveThrow_TENNO ; cost : 1
Exception: java.lang.NullPointerException
07:53:43.685 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at com.megacrit.cardcrawl.actions.common.DamageAllEnemiesAction.<init>(DamageAllEnemiesAction.java:24) ~[?:?]
	at com.megacrit.cardcrawl.actions.common.DamageAllEnemiesAction.<init>(DamageAllEnemiesAction.java:37) ~[?:?]
	at tenno_mod.cards.common.DefensiveThrow_TENNO.use(DefensiveThrow_TENNO.java:46) ~[tenno_mod.TennoMod.jar:?]
	at com.evacipated.cardcrawl.mod.hubris.patches.ZylophonePatch$MultiUse.use(ZylophonePatch.java:51) ~[Hubris.jar:?]
	at com.megacrit.cardcrawl.characters.AbstractPlayer.useCard(AbstractPlayer.java:1594) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:297) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:159) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:279) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2554) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:878) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
Game closed.

**Comment by AvangionQ** [comment]
I've since removed Defensive Throw from my deck and have avoided picking it up in future runs ... will wait for an update, hopefully this minor glitch will be remedied ...

**Comment by pkillthetoy** [comment]
Well, this is odd. I found the null in line 24 as mentioned in the logs, but it's something baked into Spire itself. I also haven't been able to get this to happen myself - though that might be in part because I didn't have any other mods besides BaseMod on during development. I tried messing around with Hubris Mod on and a Zylophone but didn't get anywhere.

If you still remember, can you tell me what you were doing right before each of the crashes? In particular, what other mods did you have enabled? Was Defensive Throw being reduced by Mummified Hand? What were you fighting? Were there multiple Defensive Throws in hand? Did you have Defensive Throw affected by Zylophone? And if you did, did any enemies die partway through?

I've also pushed a release that adds a small change, adding a missing isMultiDamage value to Defensive Throw. I don't know if this actually fixes it but it's probably good to have anyway. (https://github.com/pkillthetoy/tenno_mod/releases/tag/v0.2.1.1)

If you can, try to re-create the crash (using BaseMod's console if necessary - it's in the mod options IIRC and the BaseMod page contains instructions on how to use it), and let me know whether it still happens with the change.

**Comment by AvangionQ** [comment]
Defensive Throw was played automatically due to Big Top (Jester mod boss relic which gives automatic Mayhem). I had three copies of Defensive Throw, one of which was upgraded. Zylophone affected a different card. I'll try to recreate the crash the next time I play.

**Comment by pkillthetoy** [comment]
Okay, perfect, I was able to reproduce the issue based on that. Confirmed that D.Throw was crashing when played by Mayhem - probably because the game is looking for a target that's not supposed to be there - and that the latest change fixes it. Thanks for the catch!
