### ISSUE TITLE
Audio crash?

### ISSUE THREAD

**Issue by AvangionQ** [pkillthetoy/tenno_mod#3]
Going into a shop triggered this ... no idea why?

07:09:48.417 INFO saveAndContinue.SaveFile> Next Room: com.megacrit.cardcrawl.rooms.ShopRoom
07:09:48.419 INFO helpers.File> Attempting to save file=C:\Games\Slay the Spire\preferences\TENNO
07:09:48.420 INFO replayTheSpire.ReplayTheSpireMod> Saving Data
07:09:48.424 INFO HubrisMod> Saving Data
07:09:48.425 INFO infinitespire.InfiniteSpire> InfiniteSpire | Saving Data...
07:09:48.425 INFO helpers.File> Successfully saved file=C:\Games\Slay the Spire\preferences\TENNO
07:09:48.428 INFO helpers.AsyncSaver> Enqueue: qsize=0 file=saves\TENNO.autosave
07:09:48.428 INFO helpers.FileSaver> Dequeue: qsize=0 file=saves\TENNO.autosave
07:09:48.428 INFO helpers.File> Attempting to save file=C:\Games\Slay the Spire\saves\TENNO.autosave
07:09:48.428 INFO audio.MusicMaster> Playing SHOP
Exception: com.badlogic.gdx.utils.GdxRuntimeException: Unable to allocate audio buffers. AL Error: 40963
07:09:48.433 INFO helpers.File> Successfully saved file=C:\Games\Slay the Spire\saves\TENNO.autosave
07:09:48.431 ERROR core.CardCrawlGame> Exception caught
com.badlogic.gdx.utils.GdxRuntimeException: Unable to allocate audio buffers. AL Error: 40963
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALMusic.play(OpenALMusic.java:78) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.audio.TempMusic.<init>(TempMusic.java:61) ~[?:?]
	at com.megacrit.cardcrawl.audio.TempMusic.<init>(TempMusic.java:42) ~[?:?]
	at com.megacrit.cardcrawl.audio.MusicMaster.playTempBGM(MusicMaster.java:104) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.playBGM(AbstractRoom.java:151) ~[?:?]
	at com.megacrit.cardcrawl.rooms.ShopRoom.onPlayerEntry(ShopRoom.java:37) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.nextRoomTransition(AbstractDungeon.java:2322) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.nextRoomTransition(AbstractDungeon.java:2182) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.updateFading(AbstractDungeon.java:2851) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2539) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:878) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
Game closed.

**Comment by pkillthetoy** [comment]
Well, that's weird. At a glance that doesn't look like something this mod would have caused, since the logs point to the core game and I don't do anything involving audio (no new SFX). I've found some LibGDX threads dating back to a while ago that talk about it but don't mention fixes, so I'm inclined to think this is a rare, unrelated thing that happens.

Let me know if this happens again and I'll look deeper into it. Any extra details would help, too. Were you at least able to go into the shop properly when you relaunched the game?

**Comment by AvangionQ** [comment]
Got another audio crash, this time when killing the heart.

06:22:47.020 INFO helpers.AsyncSaver> Enqueue: qsize=0 file=preferences\TENNO
06:22:47.022 INFO helpers.FileSaver> Dequeue: qsize=0 file=preferences\TENNO
06:22:47.022 INFO helpers.AsyncSaver> Enqueue: qsize=0 file=preferences\TENNO
06:22:47.022 INFO helpers.File> Attempting to save file=C:\Games\Slay the Spire\preferences\TENNO
06:22:47.022 INFO audio.MusicMaster> Playing STS_EndingStinger_v1.ogg
06:22:47.022 INFO audio.TempMusic> ERROR: NO SUCH TEMP BGM: STS_EndingStinger_v1.ogg
06:22:47.027 INFO helpers.File> Successfully saved file=C:\Games\Slay the Spire\preferences\TENNO
06:22:47.027 INFO helpers.FileSaver> Dequeue: qsize=0 file=preferences\TENNO
Exception: com.badlogic.gdx.utils.GdxRuntimeException: Unable to allocate audio buffers. AL Error: 40963
06:22:47.029 INFO helpers.File> Attempting to save file=C:\Games\Slay the Spire\preferences\TENNO
06:22:47.030 ERROR core.CardCrawlGame> Exception caught
com.badlogic.gdx.utils.GdxRuntimeException: Unable to allocate audio buffers. AL Error: 40963
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALMusic.play(OpenALMusic.java:78) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.audio.TempMusic.<init>(TempMusic.java:61) ~[?:?]
	at com.megacrit.cardcrawl.audio.MusicMaster.playTempBgmInstantly(MusicMaster.java:132) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.monsters.AbstractMonster.playBossStinger(AbstractMonster.java:1409) ~[?:?]
	at com.megacrit.cardcrawl.monsters.AbstractMonster.onBossVictoryLogic(AbstractMonster.java:1351) ~[?:?]
	at com.megacrit.cardcrawl.monsters.ending.CorruptHeart.die(CorruptHeart.java:285) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.monsters.AbstractMonster.damage(AbstractMonster.java:809) ~[?:?]
	at com.megacrit.cardcrawl.actions.common.DamageAction.update(DamageAction.java:93) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:155) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:279) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2554) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:878) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
06:22:47.034 INFO helpers.File> Successfully saved file=C:\Games\Slay the Spire\preferences\TENNO
Controllers: removed manager for application, 0 managers active
Game closed.

**Comment by AvangionQ** [comment]
Yes, the game worked normally when returning to the shop, and again after defeating the heart a 2nd time.

**Comment by pkillthetoy** [comment]
Still no idea what's causing this, but I'll do a pass over any cards that might trying to queue effects after the end of a fight.

What other mods do you have installed? And has this ever happened without this mod?

**Comment by AvangionQ** [comment]
I don't play without mods ...

Mods installed:
AscensionMinus.jar
AscensionPlusMod.jar
BaseMod.jar
BeakedTheCultist.jar
BetterRewards.jar
BlackRuseMod.jar
BlakkMod.jar
ClockworkMod.jar
Conspire.jar
ConstructMod.jar
CustomActIVMod.jar
CustomCards.jar
DeckSortMod.jar
EnergizedSpireMod.jar
FetchMod.jar
FriendlyMinions.jar
FruityMod.jar
GluttonMod.jar
Hakumod.jar
HighlightPath.jar
Hubris.jar
InfiniteSpire.jar
JesterMod.jar
MadScienceMod.jar
RatMod.jar
RelicSorter.jar
ReplayTheSpireMod.jar
ShopMod.jar
SlimeboundMod.jar
SneckoMod.jar
SpikesRelics.jar
StrawberrySpire.jar
STS_AlwaysWhale-0.1.0.jar
sts_jedi.jar
StSLib.jar
SuperFastMode.jar
tenno_mod.TennoMod.jar
TheBlackbeardMod.jar
TheDisciple.jar
TheMystic.jar
TheNecromancer.jar
TheValiant.jar
TheWarrior.jar
TS05_Marisa.jar
WitchMod.jar
Yohane.jar
YuriMod.jar
YuyukoMod-v0.2.9.jar
